import { registerEnumType } from '@nestjs/graphql';

export enum ProductSlug {
    FREELANCER_BASIC = "FREELANCER_BASIC",
    FREELANCER_PRO = "FREELANCER_PRO",
    COMPANY_BASIC = "COMPANY_BASIC",
    COMPANY_TOP = "COMPANY_TOP",
    COMPANY_PREMIUM_ASSIGNMENT = "COMPANY_PREMIUM_ASSIGNMENT",
    COMPANY_PREMIUM_PROFILE = "COMPANY_PREMIUM_PROFILE",
    MARKETMONITOR_BASIC_VIEW = "MARKETMONITOR_BASIC_VIEW",
    MARKETMONITOR_BASIC_APPLICATION = "MARKETMONITOR_BASIC_APPLICATION",
    MARKETMONITOR_PREMIUM_VIEW = "MARKETMONITOR_PREMIUM_VIEW",
    MARKETMONITOR_PREMIUM_APPLICATION = "MARKETMONITOR_PREMIUM_APPLICATION",
    TOP_BOX = "TOP_BOX"
}


registerEnumType(ProductSlug, { name: 'ProductSlug', description: undefined })
