query getAssignmentAdmin($where: AssignmentWhereInput) {
  assignmentAdmin(where: $where) {
    ...fullAssignmentInfoFragment
    statusHistory {
      createdAt
      id
      key
      modelId
      modelType
    }
  }
}
