-- AlterTable
ALTER TABLE `Product` MODIFY `slug` ENUM('FREELANCER_BASIC', 'FREELANCER_PRO', 'COMPANY_BASIC', 'COMPANY_TOP', 'COMPANY_PREMIUM_PROFILE', 'MARKETMONITOR_BASIC_VIEW', 'MARKETMONITOR_BASIC_APPLICATION', 'MARKETMONITOR_PREMIUM_VIEW', 'MARKETMONITOR_PREMIUM_APPLICATION', 'TOP_BOX') NOT NULL;

ALTER TABLE `Plan` MODIFY `usageType` ENUM('ASSIGNMENT', 'ASSIGNMENT_VIEW', 'ASSIGNMENT_APPLICATION', 'COMPANY_PREMIUM_PROFILE', 'TOP_BOX') NOT NULL;
ALTER TABLE `Contract` MODIFY `usageType` ENUM('ASSIGNMENT', 'ASSIGNMENT_VIEW', 'ASSIGNMENT_APPLICATION', 'COMPANY_PREMIUM_PROFILE', 'TOP_BOX') NOT NULL;
ALTER TABLE `Usage` MODIFY `type` ENUM('ASSIGNMENT', 'ASSIGNMENT_VIEW', 'ASSIGNMENT_APPLICATION', 'COMPANY_PREMIUM_PROFILE', 'TOP_BOX') NOT NULL;

INSERT INTO `Product` (`externalProviderSync`, `name`, `slug`, `description`) VALUES (0, 'TOP-box', 'TOP_BOX', 'TOP-box');

SET @topBoxProductId := (SELECT id FROM `Product` WHERE `slug` = 'TOP_BOX');

INSERT INTO `Plan` (`externalProviderSync`, `slug`, `productId`, `usageType`, `usageAmount`, `usageInterval`) VALUES (0, 'top-box', @topBoxProductId, 'TOP_BOX', 0, 'NONE');
