query companies(
  $where: CompanyWhereInput!
  $orderBy: [CompanyOrderByWithRelationInput!]
  $skip: Int
  $take: Int
) {
  count: countCompanies(where: $where)
  companies(where: $where, orderBy: $orderBy, skip: $skip, take: $take) {
    id
    name
    type
    address {
      addressLine1
      postalCode
      city
    }
    cocNumber
    createdAt
    contracts {
      endDate
      plan {
        product {
          slug
        }
      }
    }
    logoImageFile {
      blobName
      container
    }
  }
}
