-- AlterTable
ALTER TABLE `Contract` MODIFY `usageType` ENUM('ASSIGNMENT', 'ASSIGNMENT_VIEW', 'ASSIGNMENT_APPLICATION', 'COMPANY_PREMIUM_PROFILE') NOT NULL;

-- AlterTable
ALTER TABLE `Plan` MODIFY `usageType` ENUM('ASSIGNMENT', 'ASSIGNMENT_VIEW', 'ASSIGNMENT_APPLICATION', 'COMPANY_PREMIUM_PROFILE') NOT NULL;

-- AlterTable
ALTER TABLE `Usage` MODIFY `type` ENUM('ASSIGNMENT', 'ASSIGNMENT_VIEW', 'ASSIGNMENT_APPLICATION', 'COMPANY_PREMIUM_PROFILE') NOT NULL;
