query VerificationSearchCompanies(
  $countryCode: VerificationCountryCodes!
  $query: String!
  $pageSize: Float
) {
  verificationSearchCompanies(
    countryCode: $countryCode
    query: $query
    pageSize: $pageSize
  ) {
    address
    city
    identificationNumber
    name
  }
}
