query mySavedSearches(
  $where: SavedSearchWhereInput
  $orderBy: [SavedSearchOrderByWithRelationInput!]
) {
  savedSearches: mySavedSearches(where: $where, orderBy: $orderBy) {
    ...savedSearchFragment
  }
}
